language: ruby
cache: bundler
rvm:
- 2.2.0
branches:
  only:
  - master
script:
# Create our _site/ dir
- mkdir build
# Set up git stuff if we are going to deploy
- |
  if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
    echo -e "Host devcenter-osdevelopers.rhcloud.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config;
    openssl aes-256-cbc -K $encrypted_635dc579ccfd_key -iv $encrypted_635dc579ccfd_iv -in ../id_rsa_deploy.enc -out id_rsa_deploy -d;
    chmod 600 id_rsa_deploy;
    eval "$(ssh-agent -s)";
    ssh-add id_rsa_deploy;
    # Start the git repo
    cd build
    git init
    git config --global user.email $USERMAIL
    git config --global user.name $USERNAME
    git remote add production $REMOTE
    git pull production master
    cd ..
  fi
# Build
- bundle exec middleman build
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then bundle exec middleman deploy; fi
env:
  global:
  - secure: gegnXkeH7IBirXATgGEo3mhTznexNiLThd/ShR8IH9608rftbFhWundVdywQ5H+6by51pGIkkZSTCmLo15E2qeRavJoDDlxFQQawWs4Cb/vGIu9kgymjZxlY259dlCV8nt3IVeX65mvgq5ejUIBBy+rdkHp/PMe81EHV8bKHus0=
  - secure: NJYiaWnSKroQh11LjyFfF6AjvOvgS81zdgkOEZcizkEZyp5FS8C4GBOn/xcn9+We+WAIb/jAxqtjBlDGdreBHQcrTxzpAFgMkifloBUPpnEkllwu8x7G2POa82bjS0/wYi5l5WZMFBMNjlKW48igYUkm3fRm7QZq8WaNxQpWQgE=
  - secure: C9tyjbuADEK9qiJZQwYkrT3y57vQ6nOLPvWo3tojjPvBe5Ec1ZTgSv/+Og4Uo6TEeSlr5G4yA+crSjZnkt9MOwf8vZ7g1KJZo4N/ErswAgEXsbwnN2BiBy1sl3wTFa2ah/sfhW40yic3bAglCxRZ6lwXg9l8o+ZxPqH4c+gvnU4=
